name: eida
description: AI Tutor Friend which helps in practicing English speaking and also makes you learn faster by correcting your grammar, pronunciation, and fluency.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  auto_route: ^3.2.4
  dartz: ^0.10.1
  uuid: ^3.0.6
  firebase_auth: ^3.3.13
  firebase_core: ^1.14.0
  get_it: ^7.2.0
  google_sign_in: ^5.2.4
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  google_fonts: ^2.3.1
  flutter_displaymode: ^0.4.0
  flutter_svg: ^1.0.3
  flutter_hooks: ^0.18.3
  cached_network_image: ^3.2.0
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  speech_to_text: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.8
  freezed: ^1.1.1
  change_app_package_name: ^1.0.0
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
